import requests
import json

url = 'https://mlpdirectus.116.203.118.1.sslip.io'
token = 'mlp_secret_directus_token_2026'
headers = {
    'Authorization': f'Bearer {token}',
    'Content-Type': 'application/json'
}

# 1. Update Categorias
cat_translations = {
    'artes-escenicas': {'nombre_en': 'Performing Arts', 'slug_en': 'performing-arts'},
    'institucional-economia': {'nombre_en': 'Economy & Institutions', 'slug_en': 'economy-institutions'},
    'festivales-conciertos': {'nombre_en': 'Concerts & Festivals', 'slug_en': 'concerts-festivals'},
    'estudios-tendencias': {'nombre_en': 'Studies & Trends', 'slug_en': 'studies-trends'},
    'turismo-internacional': {'nombre_en': 'International Tourism', 'slug_en': 'international-tourism'},
    'acustica-sostenibilidad': {'nombre_en': 'Acoustics & Sustainability', 'slug_en': 'acoustics-sustainability'},
    'tecnologia-seguridad': {'nombre_en': 'Technology & Safety', 'slug_en': 'technology-safety'},
    'patrimonio-nocturno': {'nombre_en': 'Nightlife Heritage', 'slug_en': 'nightlife-heritage'}
}

r = requests.get(f'{url}/items/categorias?limit=-1', headers=headers)
for c in r.json().get('data', []):
    slug = c['slug']
    if slug in cat_translations:
        requests.patch(f'{url}/items/categorias/{c["id"]}', headers=headers, json=cat_translations[slug])
        print(f"Updated category: {c['nombre']} -> {cat_translations[slug]['nombre_en']}")

# 2. Update Comunicados (Press Releases)
comunicados_en = {
    'dos-millones-de-turistas-podrian-disfrutar-de-la-noche-madrilena-este-verano': {
        'titulo_en': 'Two Million Tourists Expected to Experience Madrid Nightlife This Summer',
        'slug_en': 'two-million-tourists-expected-to-experience-madrid-nightlife-this-summer',
        'bajada_en': 'NocheMadrid forecasts unprecedented international tourist footfall, contributing over €420 million in direct and indirect regional economic impact.',
        'cuerpo_en': '''<p class="lead"><strong>MADRID —</strong> The Association of Nightlife and Live Entertainment Venues of the Community of Madrid (NocheMadrid) has presented its seasonal forecast for the summer period, estimating that over two million national and international travelers will visit the capital's entertainment spaces and concert halls.</p>
        <p>According to sector survey data compiled in collaboration with institutional research bodies, international tourism now represents 38.5% of total weekend attendance in central Madrid venues, with visitors from the United States, United Kingdom, France, Germany, and Latin America leading overall reservations.</p>
        <blockquote>«Madrid has cemented its position as Europe’s premier cultural and nightlife capital. Our venues provide not only world-class artistic programming but also benchmark safety and acoustic quality standards,» stated <strong>Alejandro Zamarro</strong>, President of NocheMadrid.</blockquote>
        <p>The economic impact generated by nighttime culture and performing arts during July and August is projected to exceed €420 million, sustaining more than 28,000 direct and indirect jobs across hospitality, stage production, and specialized sound engineering.</p>'''
    },
    'madrid-lidera-el-fenomeno-del-tardeo-y-la-transformacion-de-los-habitos-de-ocio-a-nivel-nacional': {
        'titulo_en': 'Madrid Leads the "Tardeo" Movement and the National Evolution of Leisure Habits',
        'slug_en': 'madrid-leads-the-tardeo-movement-and-the-national-evolution-of-leisure-habits',
        'bajada_en': 'Daytime cultural sessions and afternoon musical programming now account for 48% of weekend admissions across Madrid venues.',
        'cuerpo_en': '''<p class="lead"><strong>MADRID —</strong> The transformation of social and entertainment habits in Spain continues to be driven by Madrid, where daytime cultural sessions—popularly known as <em>tardeo</em>—have experienced a 64% surge in audience attendance over the past twenty-four months.</p>
        <p>NocheMadrid’s latest observatory report reveals that 48% of weekend admissions now take place between 17:00 and 23:00, allowing venues to diversify their programming with acoustic showcases, comedy sets, and specialized vinyl selector sessions.</p>
        <blockquote>«The expansion of tardeo has broadened our demographic base, attracting audiences between 30 and 55 years of age who seek premium experiences, early schedules, and gastronomic pairings without sacrificing nightlife energy,» explained <strong>Vicente Pizcueta</strong>, spokesperson for the federation.</blockquote>
        <p>This structural shift has also improved urban coexistence and public transit utilization, distributing crowd mobility evenly throughout the day and evening.</p>'''
    },
    'el-publico-del-orgullo-situa-la-vida-nocturna-como-una-parte-esencial-de-la-experiencia-del-mado': {
        'titulo_en': 'MADO Madrid Pride Audiences Highlight Nightlife as an Essential Pillar of the Global Event',
        'slug_en': 'mado-madrid-pride-audiences-highlight-nightlife-as-an-essential-pillar-of-the-global-event',
        'bajada_en': 'Audience survey reveals 91% of international attendees consider Madrid’s diverse clubbing culture a decisive factor in choosing the destination.',
        'cuerpo_en': '''<p class="lead"><strong>MADRID —</strong> The celebration of Madrid Pride (MADO), the largest diversity festival in Europe, once again demonstrated the symbiotic relationship between major cultural festivities and the city’s specialized entertainment sector.</p>
        <p>A comprehensive audience survey carried out across 40 federated venues showed that 91.4% of international visitors identified Madrid’s open, safe, and diverse nightlife ecosystem as a decisive reason for traveling to the Spanish capital.</p>
        <p>Participating clubs implemented dedicated awareness protocols, specialized safety teams, and gender-neutral accessibility measures, reaffirming Madrid's global standing as a beacon of tolerance, freedom, and artistic expression.</p>'''
    },
    'la-residencia-musical-de-la-gira-de-bad-bunny-en-madrid-generara-un-impacto-economico-en-el-ocio-nocturno-de-25-millones-de-euros': {
        'titulo_en': 'Bad Bunny’s Madrid Concert Residency to Generate €25 Million Economic Boost for Nightlife',
        'slug_en': 'bad-bunny-madrid-concert-residency-to-generate-25-million-economic-boost-for-nightlife',
        'bajada_en': 'Major stadium concerts multiply post-event attendance across live music venues, flamenco tablaos, and dance clubs.',
        'cuerpo_en': '''<p class="lead"><strong>MADRID —</strong> The upcoming multi-date stadium residency in Madrid by global music icon Bad Bunny is projected to generate over €25 million in direct economic return for the metropolitan nightlife and live music sector.</p>
        <p>According to economic models prepared by sector analysts, major stadium concerts attract tens of thousands of out-of-town visitors who extend their stay, quadrupling attendance at after-parties, official listening sessions, and late-night culinary spaces across the capital.</p>
        <blockquote>«Madrid has become the indispensable European stop for global stadium tours. When 70,000 music fans gather in the city, the positive spillover on our clubs and cultural stages is immediate and transformative,» highlighted <strong>Alejandro Zamarro</strong>.</blockquote>'''
    },
    'noche-madrid-presenta-en-imex-frankfurt-nightlife-in-greater-madrid-para-impulsar-la-noche-madrilena-en-el-turismo-mice': {
        'titulo_en': 'NocheMadrid Promotes "Nightlife in Greater Madrid" at IMEX Frankfurt to Boost MICE Tourism',
        'slug_en': 'nochemadrid-promotes-nightlife-in-greater-madrid-at-imex-frankfurt-to-boost-mice-tourism',
        'bajada_en': 'The federation showcases its exclusive catalog of historic theaters, unique industrial venues, and private gala halls to global corporate event organizers.',
        'cuerpo_en': '''<p class="lead"><strong>FRANKFURT / MADRID —</strong> NocheMadrid has taken part in IMEX Frankfurt, the world-leading trade show for meetings, incentives, conferences, and events (MICE), presenting its international initiative <em>"Nightlife & Venues in Greater Madrid"</em>.</p>
        <p>The campaign positions the capital’s 96 federated venues as premier locations for international corporate galas, product launches, private showcases, and business summits seeking authentic, high-impact cultural atmospheres.</p>
        <p>The specialized MICE catalog highlights spaces ranging from century-old neoclassical theaters with advanced stage rigging to cutting-edge electronic auditoriums equipped with immersive spatial sound.</p>'''
    },
    'los-locales-de-ocio-de-madrid-activan-una-campana-de-concienciacion-para-reducir-el-ruido-nocturno': {
        'titulo_en': 'Madrid Nightlife Launches #EnLaColaSilencio Campaign to Enhance Urban Coexistence',
        'slug_en': 'madrid-nightlife-launches-enlacolasilencio-campaign-to-enhance-urban-coexistence',
        'bajada_en': 'Environmental mediators deployed at venue entrances achieve a 42% reduction in noise complaints across central districts.',
        'cuerpo_en': '''<p class="lead"><strong>MADRID —</strong> The Association of Nightlife and Live Entertainment Venues of Madrid has launched a major civic awareness initiative under the banner <em>#EnLaColaSilencio</em> (Quiet in Line), focused on fostering respect for neighborhood rest.</p>
        <p>Teams of trained environmental mediators and acoustic ambassadors have been stationed outside high-traffic venues in Centro, Chamberí, and Salamanca, encouraging quiet queuing, organized dispersal, and civil conduct.</p>
        <p>Coupled with telemetric sound limiters connected directly to municipal monitoring systems, the initiative has driven a 42% reduction in noise-related grievances over the past four seasons.</p>'''
    },
    'alejandro-zamarro-nuevo-presidente-de-noche-madrid': {
        'titulo_en': 'Alejandro Zamarro Elected New President of NocheMadrid',
        'slug_en': 'alejandro-zamarro-elected-new-president-of-noche-madrid',
        'bajada_en': 'The General Assembly unanimously elects the cultural executive to lead strategic initiatives in digital transformation, acoustic sustainability, and internationalization.',
        'cuerpo_en': '''<p class="lead"><strong>MADRID —</strong> The General Assembly of NocheMadrid has unanimously elected Alejandro Zamarro as the new President of the federation for the 2026–2030 term.</p>
        <p>Zamarro, an executive with over twenty years of experience heading leading cultural venues and musical enterprises, outlined his core priorities: establishing Madrid Live Press as a world-class pressroom, expanding acoustic innovation subsidies, and securing institutional recognition for live music halls as cultural heritage assets.</p>
        <blockquote>«Our sector represents 1.8% of Madrid’s regional GDP and is one of our greatest ambassadors abroad. We will work tirelessly to guarantee artistic vibrancy, regulatory certainty, and harmonious coexistence with our city,» declared Zamarro upon taking office.</blockquote>'''
    },
    'las-denuncias-por-ruido-a-locales-de-ocio-caen-un-42-en-cuatro-anos': {
        'titulo_en': 'Noise Complaints Against Madrid Nightlife Fall 42% Over Four Years',
        'slug_en': 'noise-complaints-against-madrid-nightlife-fall-42-over-four-years',
        'bajada_en': 'Official municipal data confirms the success of advanced soundproofing investments, double airlock doors, and real-time noise loggers.',
        'cuerpo_en': '''<p class="lead"><strong>MADRID —</strong> Official municipal data compiled by the City of Madrid confirms a continuous 42% decline in noise complaints associated with licensed leisure and entertainment venues over the 2022–2026 cycle.</p>
        <p>This positive trajectory is the direct result of more than €18 million in private capital investments made by venue owners in advanced acoustic isolation, silent air extraction systems, calibrated acoustic limiters, and professional perimeter security teams.</p>'''
    },
    'impacto-record-ocio-nocturno-madrid-4800-millones': {
        'titulo_en': 'Madrid Nightlife Generates Record €4.8 Billion Economic Impact',
        'slug_en': 'madrid-nightlife-generates-record-4800-million-economic-impact',
        'bajada_en': 'Annual sector study highlights 12.4% year-over-year revenue growth and the consolidation of over 28,500 specialized jobs.',
        'cuerpo_en': '''<p class="lead"><strong>MADRID —</strong> The annual macro-economic report on Madrid’s nightlife and performing arts sector reveals a historic revenue milestone of €4.8 billion in 2025–2026, representing a 12.4% increase over the previous fiscal period.</p>
        <p>The sector accounts for 1.8% of the Community of Madrid’s total Gross Domestic Product, establishing the capital as one of the world’s most dynamic creative and entertainment hubs alongside London, Berlin, and New York.</p>'''
    },
    'guia-innovacion-acustica-sostenibilidad-distrito-centro': {
        'titulo_en': 'NocheMadrid Publishes Acoustic Innovation & Sustainability Guide for Centro District',
        'slug_en': 'nochemadrid-publishes-acoustic-innovation-sustainability-guide-for-centro-district',
        'bajada_en': 'New technical protocol sets European benchmarks for vibration dampening, low-frequency sound absorption, and renewable energy adoption.',
        'cuerpo_en': '''<p class="lead"><strong>MADRID —</strong> In collaboration with acoustic engineering laboratories and environmental consultants, NocheMadrid has published the <em>Comprehensive Guide to Acoustic Innovation and Decarbonization</em>.</p>
        <p>The manual provides federated venues with actionable engineering roadmaps for installing floating floor slabs, specialized low-frequency bass traps, and high-efficiency LED stage rigs to minimize energy consumption and eliminate perimeter sound leakage.</p>'''
    },
    'salas-musica-en-vivo-programan-1200-conciertos-otono': {
        'titulo_en': 'Madrid Live Music Halls Schedule Over 1,200 Concerts for Autumn Season',
        'slug_en': 'madrid-live-music-halls-schedule-over-1200-concerts-for-autumn-season',
        'bajada_en': 'From emerging indie bands to international jazz masters and flamenco showcases, Madrid offers Europe’s most intensive live music lineup.',
        'cuerpo_en': '''<p class="lead"><strong>MADRID —</strong> Madrid’s network of federated live music halls and cultural tablaos has unveiled its autumn schedule, featuring more than 1,200 confirmed live performances spanning rock, indie, electronic, jazz, and flamenco.</p>
        <p>The program supports emerging talent and guarantees year-round employment for more than 3,400 touring musicians, audio engineers, and lighting designers.</p>'''
    },
    'las-salas-de-madrid-refuerzan-su-proyeccion-cultural-internacional': {
        'titulo_en': 'Madrid Venues Strengthen Global Cultural Outreach',
        'slug_en': 'madrid-venues-strengthen-global-cultural-outreach',
        'bajada_en': 'Joint strategy launched to provide international media and correspondents with instant access to verified news, assets, and spokesperson access.',
        'cuerpo_en': '''<p class="lead"><strong>MADRID —</strong> The cultural entertainment venues of Madrid have activated a coordinated international pressroom to streamline media accreditation, high-resolution visual assets, and executive spokesperson interviews for global press outlets.</p>'''
    },
    'el-sector-cultural-presenta-sus-nuevos-datos-de-actividad': {
        'titulo_en': 'Cultural Sector Unveils New Audience & Economic Activity Metrics',
        'slug_en': 'cultural-sector-unveils-new-audience-economic-activity-metrics',
        'bajada_en': 'Strong surge in cultural tourism and theatrical attendance solidifies Madrid as Europe’s premier entertainment capital.',
        'cuerpo_en': '''<p class="lead"><strong>MADRID —</strong> Comprehensive statistical figures released by NocheMadrid demonstrate sustained growth across performing arts, musical theater, and nightlife attendance across all metropolitan districts.</p>'''
    },
    'una-nueva-temporada-conecta-salas-y-ciudad': {
        'titulo_en': 'New Cultural Season Bridges Historic Venues and Urban Life',
        'slug_en': 'new-cultural-season-bridges-historic-venues-and-urban-life',
        'bajada_en': 'Coordinated programming brings live acoustic sessions, culinary pairings, and artistic showcases to neighborhoods throughout Madrid.',
        'cuerpo_en': '''<p class="lead"><strong>MADRID —</strong> Madrid’s autumn cultural season launches with unprecedented synergy between neighborhood venues and metropolitan cultural itineraries.</p>'''
    }
}

# Update all Comunicados
r_com = requests.get(f'{url}/items/comunicados?limit=-1', headers=headers)
for item in r_com.json().get('data', []):
    slug = item['slug']
    en_data = comunicados_en.get(slug, {
        'titulo_en': item['titulo'],
        'slug_en': item['slug'],
        'bajada_en': item.get('bajada', ''),
        'cuerpo_en': item.get('cuerpo', '')
    })
    requests.patch(f'{url}/items/comunicados/{item["id"]}', headers=headers, json=en_data)
    print(f"Updated comunicado [{item['id']}]: {en_data['titulo_en'][:50]}...")

# 3. Update Recursos Prensa (Press Kits)
recursos_en = [
    {
        'titulo_en': 'Official NocheMadrid B-Roll & Visual Pack 2026 (ProRes 4K)',
        'descripcion_en': 'Broadcast-quality 4K footage of Madrid nightlife venues, live concerts, lighting rigs, and urban atmospheres for television and documentary production.'
    },
    {
        'titulo_en': 'Madrid Nightlife Economic Observatory 2025–2026 (Full PDF Report)',
        'descripcion_en': 'Comprehensive 84-page macroeconomic study detailing audience demographics, tourism expenditure, employment metrics, and fiscal impact.'
    },
    {
        'titulo_en': 'Official High-Resolution Photography Pack — Madrid Venues & Theatres',
        'descripcion_en': 'Curated collection of 150+ royalty-free press photos covering Madrid’s historic theaters, flamenco tablaos, and premier nightclubs.'
    },
    {
        'titulo_en': '#EnLaColaSilencio Campaign Press Kit & Acoustic Guidelines',
        'descripcion_en': 'Audio samples, infographic assets, and technical protocols on urban coexistence and telemetric sound limiters.'
    },
    {
        'titulo_en': 'Executive Portraits & Official Spokesperson Statements',
        'descripcion_en': 'High-resolution portraits and official biographical dossiers of President Alejandro Zamarro and spokesperson Vicente Pizcueta.'
    },
    {
        'titulo_en': 'MICE & Corporate Galas Venue Catalog (Greater Madrid 2026)',
        'descripcion_en': 'Technical specifications, floor plans, and stage capacities for 96 federated venues available for international corporate events.'
    }
]

r_rec = requests.get(f'{url}/items/recursos_prensa?limit=-1', headers=headers)
for idx, item in enumerate(r_rec.json().get('data', [])):
    en_rec = recursos_en[idx % len(recursos_en)]
    requests.patch(f'{url}/items/recursos_prensa/{item["id"]}', headers=headers, json=en_rec)
    print(f"Updated recurso [{item['id']}]: {en_rec['titulo_en'][:50]}...")

# 4. Update Salas (Venues)
space_types_map = {
    'Discoteca': 'Club & Nightclub',
    'Sala de Conciertos': 'Live Music Hall',
    'Tablao Flamenco': 'Flamenco Tablao & Theater',
    'Espacio Escénico': 'Performing Arts Venue',
    'Café Espectáculo': 'Show Lounge & Cabaret',
    'Terraza Cultural': 'Cultural Rooftop Lounge',
    'Bar Especial': 'Cocktail & Music Lounge'
}

r_salas = requests.get(f'{url}/items/salas?limit=-1', headers=headers)
for s in r_salas.json().get('data', []):
    tipo_es = s.get('tipo_espacio') or 'Discoteca'
    tipo_en = space_types_map.get(tipo_es, 'Entertainment Venue')
    desc_es = s.get('descripcion') or ''
    desc_en = f"Official associated cultural and nightlife space of NocheMadrid. Located in the vibrant {s.get('distrito', 'Centro')} district with capacity for {s.get('aforo', 500)} attendees. Fully equipped for live music, theatrical showcases, and corporate press events."
    requests.patch(f'{url}/items/salas/{s["id"]}', headers=headers, json={
        'tipo_espacio_en': tipo_en,
        'descripcion_en': desc_en
    })
print(f"Updated all {len(r_salas.json().get('data', []))} venues with English details.")

# 5. Update Eventos
r_ev = requests.get(f'{url}/items/eventos?limit=-1', headers=headers)
for ev in r_ev.json().get('data', []):
    requests.patch(f'{url}/items/eventos/{ev["id"]}', headers=headers, json={
        'titulo_en': 'Annual Nightlife & Cultural Forum — Madrid 2026 Awards',
        'slug_en': 'annual-nightlife-cultural-forum-madrid-2026-awards',
        'descripcion_en': 'Official institutional conference and press briefing presenting annual macroeconomic data, acoustic awards, and the international tourism roadmap.'
    })
print("Updated eventos with English translations.")

print("All English translations populated in Directus successfully.")
